# Config file for automatic testing at travis-ci.org

branches:
 only:
  - master

language: python

matrix:
  include:
    - os: linux
      python: "3.4"

    - os: linux
      python: "3.3.5"

    - os: linux
      python: "2.7"

    - os: osx
      language: generic
      env:
        - PYTHONVERSION=3.4.5

    - os: osx
      language: generic
      env:
        - PYTHONVERSION=3.3.6

    - os: osx
      language: generic
      env:
        - PYTHONVERSION=2.7.12

before_install:
  - pip install scikit-ci

install:
  - ci before_install
  - ci install

before_script:
  - ci before_build

script:
  - ci build
  - ci test

after_success:
  - ci after_test

