---

branches:
 only:
  - master

version: "0.0.1.{build}"

environment:
  matrix:

    # Visual Studio (Python 2 & 3, 32 & 64 bit)
    - PYTHON_DIR: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"
      BLOCK: "0"
      EXPECTED_PYTHON_VERSION: 2,7,12

    - PYTHON_DIR: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"
      BLOCK: "0"
      EXPECTED_PYTHON_VERSION: 2,7,12

    - PYTHON_DIR: "C:\\Python35"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "32"
      BLOCK: "0"
      EXPECTED_PYTHON_VERSION: 3,5,2

    - PYTHON_DIR: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "64"
      BLOCK: "0"
      EXPECTED_PYTHON_VERSION: 3,5,2

init:
  - ps: "\
      iex (\
        (New-Object Net.Webclient).DownloadString(\
          'https://raw.githubusercontent.com/\
            appveyor/ci/master/scripts/enable-rdp.ps1'\
        )\
      )"

  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: "\
    if (\
      $env:APPVEYOR_PULL_REQUEST_NUMBER -and \
      $env:APPVEYOR_BUILD_NUMBER -ne (\
        (\
          Invoke-RestMethod \
            ` https://ci.appveyor.com/api/projects/\
                $env:APPVEYOR_ACCOUNT_NAME/\
                $env:APPVEYOR_PROJECT_SLUG/\
                history?recordsNumber=50\
        ).builds | ` Where-Object pullRequestId -eq \
                                  $env:APPVEYOR_PULL_REQUEST_NUMBER\
      )[0].buildNumber\
    ) { ` \
      throw \"There are newer queued builds \
              for this pull request, failing early.\" \
    }"

  - python.exe -m pip install scikit-ci

install:
  - python -m ci before_install
  - python -m ci install

build_script:
  - python -m ci before_build
  - python -m ci build"

test_script:
  - python -m ci test"

after_test:
  - python -m ci after_test"

on_finish:
  - ps: "\
      if ($Env:BLOCK -ceq \"1\") {
        $blockRdp = $true ; \
        iex (\
          (New-Object Net.Webclient).DownloadString(\
            'https://raw.githubusercontent.com/\
             appveyor/ci/master/scripts/enable-rdp.ps1'\
          )\
        )
      }"

on_failure:
  - ps: "Get-EventLog AppVeyor -newest 10 | Format-List"

matrix:
  fast_finish: false

shallow_clone: false
