---

branches:
 only:
  - master

version: "0.0.1.{build}"

environment:
  matrix:

    # Visual Studio (Python 2 & 3, 32 & 64 bit)
    - PYTHON_DIR: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"
      BLOCK: "0"
      # Used for testing
      EXPECTED_PYTHON_VERSION: 2.7.13
      EXPECTED_PYTHON_ARCH: 32

    - PYTHON_DIR: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"
      BLOCK: "0"
      # Used for testing
      EXPECTED_PYTHON_VERSION: 2.7.13
      EXPECTED_PYTHON_ARCH: 64

    - PYTHON_DIR: "C:\\Python35"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "32"
      BLOCK: "0"
      # Used for testing
      EXPECTED_PYTHON_VERSION: 3.5.3
      EXPECTED_PYTHON_ARCH: 32

    - PYTHON_DIR: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "64"
      BLOCK: "0"
      # Used for testing
      EXPECTED_PYTHON_VERSION: 3.5.3
      EXPECTED_PYTHON_ARCH: 64

cache:
  - C:\\cmake-3.6.2
  - C:\\Downloads

install:
  - ps: appveyor/rolling-build.ps1
  - python -m pip install scikit-ci==0.12.0
  - python -m ci install

build_script:
  - python -m ci build

test_script:
  - python -m ci test

after_test:
  - python -m ci after_test

on_finish:
  - ps: appveyor/enable-worker-remote-access.ps1 -check_for_block

artifacts:
  - path: dist\*

on_failure:
  - ps: "Get-EventLog AppVeyor -newest 10 | Format-List"

matrix:
  fast_finish: false

shallow_clone: false
